### ISSUE TITLE
add methods for reading and writting data from an offset

### ISSUE THREAD

**Issue by wanderer** [ipfs/js-ipfs-unixfs-engine#172]
It would be nice to support an option to read and write data from an offset. 
```javascript
const reader = require('ipfs-unixfs-engine').reader
promise = reader(CID, offset, length)
```
```javascript
const writer = require('ipfs-unixfs-engine').writer
promise = writer(CID, offset, data)
```

**Comment by diasdavid** [comment]
There have been more requests for this feature - https://github.com/ipfs/js-ipfs/issues/348 I agree that we should have it. A simple version of dropping bytes would be simple enough to achieve the API, then we can optimize its perf.

**Comment by diasdavid** [comment]
The writer is a bit more complex, not sure if it belongs here. Essentially what would need to be done is to fetch the whole file, modify and chunk the whole thing again. There will be a bunch of nodes that get reused, but this slight bit modification would have to be aware of the graph builder and chunker used.

**Comment by wanderer** [comment]
> this slight bit modification would have to be aware of the graph builder and chunker used.

right, and also different chunking schema are going to have different optimal offset units too

**Comment by achingbrain** [comment]
The ship this was shipped on set sail ages ago 🚢 ⚓️ 📦 🚀
