### ISSUE TITLE
Browser performance issue

### ISSUE THREAD

**Issue by Beanow** [ipfs/js-ipfs-unixfs-engine#187]
In a very similar fashion to https://github.com/libp2p/js-libp2p-secio/issues/92 I find that adding large files spends a huge amount of time garbage collecting buffers.

I.e. adding a 55MB file cost me about 20 seconds doing >10k GC runs on Firefox.

I'm in the process of narrowing down the culprit, but it seems to be the `pull-block` implementation used in the fixed size chunker.

**Comment by diasdavid** [comment]
@Beanow could you share an update of the results with the new pull-block?

**Comment by Beanow** [comment]
@diasdavid pull-block 1.2.1 makes a huge difference.
As a test I added 5 large files, totaling 334MB.

**pull-block 1.2.0**
- Takes minutes to complete
- Firefox freezes regularly
- Up to 15K garbage collection runs **per file**

**pull-block 1.2.1**
- Took ~24 seconds
- Some stutters, but no freezing
- 2400 GC's **total**

A new install of IPFS does not bring it in yet though.
`"pull-block": "^1.2.1"` in the root package.json was required.

**Comment by diasdavid** [comment]
Wowow! That is incredible. Thanks so much @Beanow!

**Comment by diasdavid** [comment]
Continuous on https://github.com/ipfs/js-ipfs-unixfs-engine/pull/190
