### ISSUE TITLE
README question

### ISSUE THREAD

**Issue by mitra42** [ipfs/js-ipfs-unixfs-engine#188]
Thanks for the simple example, certainly helps understand what you are trying to do. BUT ... two improvements would help.

1: Could you give an example of code that would result in "dag or ipld-resolver instance", that is far from obvious. 
2: You refer to file and file2 in the example, but I think that's a typo since file and file2 aren't defined, and you want "/tmp/foo/bar" instead ?

**Comment by diasdavid** [comment]
Thanks for reporting that. Fixed with https://github.com/ipfs/js-ipfs-unixfs-engine/commit/d78f82c2b697d81ceb951cb4d6de6fec6b889483

the `ipld-resolver` is the ipld-resolver module on npm, which you can find it here https://github.com/ipld/js-ipld-resolver
