### ISSUE TITLE
feat: .get(<cid array>) from the DAG API

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs-unixfs-engine#216]
So that the DHT can handle multiple block requests without blasting hundreds of requests. Needed for https://github.com/ipfs/js-ipfs/pull/856

**Comment by diasdavid** [comment]
Quick correction, this module uses the DAG API and therefore needs and function call there that can return multiple IPLD nodes.

This is intertwined with the GraphSync effort. @vmx do you already have code for this?

**Comment by vmx** [comment]
No, I haven't any code for this yet.

**Comment by diasdavid** [comment]
@achingbrain now that @vmx shipped getMany on IPLD, can you look into shipping this one? It is needed for the DHT effort https://github.com/ipfs/js-ipfs/pull/856

**Comment by achingbrain** [comment]
Just checking what the requirement is here - after chatting with @vasco-santos it doesn't sound like there's much to do from a DHT Endeavour perspective?

We can expose `ipld.getMany` as `ipfs.dag.getMany` (or perhaps just chain through if an array of `CID`s is passed to `ipfs.dag.get`), and then this module can use it when exporting a  `DAGNode`s worth of `DAGLink`s which should be a nice performance improvement, but it doesn't sound like that would hold up the DHT effort.

@diasdavid have I missed something?  What changes did you have in mind that would resolve this issue?

**Comment by diasdavid** [comment]
It doesn't need to block the DHT effort but it will quickly be a issue if we do a DHT query for every single block we need to fetch. Using the .getMany is a first step towards a maintainable solution.

**Comment by achingbrain** [comment]
I've implemented this in the shiny new decomposed [`ipfs/js-ipfs-unixfs-exporter`](https://github.com/ipfs/js-ipfs-unixfs-exporter/pull/2) repo.
