### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-unixfs-engine#28]
- [x] get importer up to the new path + stream format
- [x] integrate exporter onto js-ipfs
- [x] create docs of how importer and exporter works

Some notes:

	var importer = new unixFSE.import()
		importer.add({path: , stream:)
			chunk the file, store the hash
		importer.finish()

		- default “no flush”, in the future, support flush
		- each time a file is hashed and added, emit an event with that filepath and hash
		- when the dir gets added, also emit an event for that
		- use a env variable to use main IPFS repo, just for the tests
		- I can sort (at ipfs-core) before printing :)
			
	var exporter = new unixFSE.export()
		each time it hits a file emit an event with a file and write to the stream

Proposal:

I want to rename this module to `unixfs-engine`, because it is what it really is, the agnostic file importer will be done later, this is not prepared in any sense to support different layouts (nor do we know yet how to achieve that).

**Comment by nginnever** [comment]
A name change is something that I think is a really good idea since data-importing does not cover the other half of what the module is doing. I really like the name Unixfs-engine.

**Comment by diasdavid** [comment]
moar notes (from last call)

var importer = new unixFSE.importer()

    importer.add({path: , stream:)
        chunk the file, store the hash

    importer.finish()

    - default “no flush”, in the future, support flush
    - each time a file is hashed and added, emit an event with that filepath and hash
    - when the dir gets added, also emit an event for that
    - use a env variable to use main IPFS repo, just for the tests
    - It can sort (at ipfs-core) before printing :)

NO FLUSH
    
importer.add({path: /a/foo.txt, stream: <>}
-> 
1) foo gets chunked and converted to unixfs/merkledag
2) importer.on('something', {path:/a/foo.txt, hash: QmHASHafootxt}
importer.add({path: /a/baz.txt, stream: <>}
1) foo gets chunked and converted to unixfs/merkledag
2) importer.on('something', {path:/a/foo.txt, hash: QmHASHafootxt}

...
importer.finish()
importer.on('something', {path: /a, hash: QmHASHofdirA}


FLUSH ON
    
importer.add({path: /a/foo.txt, stream: <>}
-> 
1) foo gets chunked and converted to unixfs/merkledag
2) importer.on('something', {path:/a/foo.txt, hash: QmHASHafootxt}
3) importer.on('something', {path:/a, hash: QmHASHdirofA}
importer.add({path: /a/baz.txt, stream: <>}
1) foo gets chunked and converted to unixfs/merkledag
2) importer.on('something', {path:/a/foo.txt, hash: QmHASHafootxt}
3) importer.on('something', {path:/a, hash: QmHASHnewDirofA}

...
importer.finish()
importer.on('something', {path: /a, hash: QmHASHofdirA}

**Comment by diasdavid** [comment]
@nginnever can we get a status update on the js-ipfs integration? Thank you.

**Comment by diasdavid** [comment]
Tracking at: https://github.com/ipfs/js-ipfs/pull/156

**Comment by diasdavid** [comment]
@nginnever would you be able to update the documentation of this module, please? Thank you :)

**Comment by nginnever** [comment]
Sure, will do that today!
