### ISSUE TITLE
Support for UnixFS Sharding + support balanced & trickle dag

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-unixfs-engine#45]
When spec is ready

**Comment by noffle** [comment]
Is there a wip spec? Could you link to it (and/or any other relevant docs)?

**Comment by diasdavid** [comment]
There you go. Gist is that we figured out how to do the Sharding while at NYC, waiting on @jbenet to lay down the spec.

- https://github.com/ipfs/specs/issues/32
- https://github.com/ipfs/specs/issues/10
- https://github.com/ipfs/notes/issues/76
- https://github.com/ipfs/go-ipfs/issues/2247#issuecomment-211441820

**Comment by diasdavid** [comment]
@whyrusleeping can you share how is the 'file wrapping' happening in go-ipfs currently? If I'm not mistaken, it is something like ' each time we reach 174 links in a file dag node, we wrap it in another dagnode and add the chunks to the new one'

**Comment by diasdavid** [comment]
@whyrusleeping is there a spec in progress for the sharding? plus probably some impl details to make it faster? It would also be good to have the trickle dag documented and something saying when we are moving to it so that we can prepare.

**Comment by dignifiedquire** [comment]
Does it make sense to do this before IPLD, as far as I understood the spec would change with IPLD?

**Comment by whyrusleeping** [comment]
The [changes to the unixfs protobuf](https://github.com/ipfs/go-ipfs/pull/3042/commits/f9ff1d6b83e74ce56dff6a60109254b316012b8c#diff-7e6bd2fe376f37f54b3dda741384d37dL9)  are the most relevant.

Beyond that, a few notes:
- using murmur3-64 over the directory entry names
- i'm using the unixfs `Data` field to hold the bitfield.
- All link names are prefixed with the hex representation of their index within the bitfield. Nested shards link names are just the hex number.
- When creating new directories, we leave them unsharded up until some threshold which is at the moment arbitrarily set to 1000

Beyond that, it follows the HAMT algorithms

Other than that, it follows the general

**Comment by jbenet** [comment]
> - using murmur3-64 over the directory entry names

must be configurable. 

@whyrusleeping do you recall where we put the HAMT notes we took on a pad once? it had the construction in IPLD and the mapping form protobuf to IPLD.

**Comment by whyrusleeping** [comment]
> must be configurable.

Yes, of course. Take a look at the [linked changes to the protobuf](https://github.com/ipfs/go-ipfs/pull/3042/commits/9dde2939817d2116329d87aa00865c50f6a214b1#diff-7e6bd2fe376f37f54b3dda741384d37dR10)

As for the pad, i'm not finding it in my chrome history... Do you remember if we used a riseup pad for that?

**Comment by jbenet** [comment]
Yeah riseup most likely :/

**Comment by diasdavid** [comment]
@whyrusleeping, @pgte just pinged me about the max number of leaves per node and from the diagram we sketched a couple of weeks ago, the impression I got was that it is 172 data leaves + nLayerRepeat (default 4) + 1 link for the next level, total of 177.

![trickle-dag](https://cloud.githubusercontent.com/assets/1211152/21593730/30d77e4e-d112-11e6-9b8a-408d96f52d65.jpg)

However, just to be sure, I tested adding a big file with the TrickleDAG and got 183 Links

```
ipfs object links QmHash.. | wc -l
     183
```

Where are the extra 6 coming from?

**Comment by whyrusleeping** [comment]
the trickledag doesnt have a max width, but you can compute the expected width of a tree of a given depth by taking `num_data_leaves + (depth * nLayerRepeat)`.

Not having a max width is fine because by the time we get to max blocksize, we end up having a file with more bits than there are atoms in the planet, or something

**Comment by whyrusleeping** [comment]
@diasdavid The key here is that everything about the trickledag is recursive.

**Comment by diasdavid** [comment]
Got it now :) 

![trickle-dag](https://cloud.githubusercontent.com/assets/1211152/21658873/88d817f4-d2c8-11e6-8b88-35eadb20fc98.jpg)

It keeps repeating itself as it goes, increasing the level of depth each time. @pgte does the graph above help to clarify this last detail?

**Comment by pgte** [comment]
Specially the reduction being asynchronous has made this quite interesting to solve.. :)

**Comment by diasdavid** [comment]
BalancedDAG + TrickleDAG is on https://github.com/ipfs/js-ipfs-unixfs-engine/pull/118 thanks to @pgte and Sharding/HAMT is on its way! :D

**Comment by diasdavid** [comment]
@pgte has shipped all of this!! !:D check it out on the last release of js-ipfs :)
